apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend.fullname" . }}  # Helm 템플릿으로 서비스 이름 생성
  labels:
    {{- include "frontend.labels" . | nindent 4 }}  # 공통 레이블 적용
spec:
  type: {{ .Values.service.type }}  # values.yaml에서 서비스 타입 가져오기
  ports:
    - port: {{ .Values.service.port }}  # 외부 포트
      targetPort: {{ .Values.service.targetPort }}  # 컨테이너 포트
      protocol: TCP
      name: http  # 포트 이름
  selector:
    {{- include "frontend.selectorLabels" . | nindent 4 }}  # 파드 셀렉터 